sudo: required

env:
  global:
    - TAG=master DOCKER_TAG=automatic
    
matrix:
  # TARGET = Base image architecture to be used
  # ARCH = qemu binary to be downloaded from https://github.com/multiarch/qemu-user-static/releases
  # TAG = Tag to be applied to the image when upload to DockerHub
  - TARGET=arm64v8 ARCH=aarch64 TAG=arm64 RELEASE=arm64
    
services:
  - docker

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "Building octroprint branch/tag $TAG into mc303/octoprint-arm64v8:$DOCKER_TAG"
  - docker build --build-arg tag=$TAG -t mc303/octoprint-arm64v8:$DOCKER_TAG .
  - if [[ "$DOCKER_TAG" != "automatic" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [[ "$DOCKER_TAG" != "automatic" ]]; then docker push mc303/octoprint-arm64v8:$DOCKER_TAG; fi
